apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eks-nginx
  name: eks-nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: eks-nginx
  template:
    metadata:
      labels:
        app: eks-nginx
    spec:
      containers:
      - image: 543478887384.dkr.ecr.ap-northeast-2.amazonaws.com/k8s-cluster-repo:v1.0

        name: eks-nginx

